### ISSUE TITLE
Invalid Auth token 

### ISSUE THREAD

**Issue by ollebergkvist** [DopplerHQ/vscode#31]
I get "Invalid Auth Token" when pressing "Setup Doppler" in the Doppler tab for the extension.

I can't see any way to link his auth token manually.

I'm authenticated with doppler and can use the cli perfectly. I've tried to reinstall the extension several times.
I believe the extension is linked to an old auth token that has been deactivated.

How to solve this?

**Comment by watsonian** [comment]
@ollebergkvist Most likely you have another CLI login on your machine. Can you run `doppler configure --all | grep "token"` in your shell and see what tokens show up? The last column is the scope the token is active for. A typical setup will have one for the `/` scope. If there are other tokens with a different scope, that token will be active at that scope and any subdirectories under it. One of the easiest ways to fix this is to reset your CLI environment using `doppler configure reset`. You would then have to run `doppler setup` again anywhere you had previously, but it should solve the auth token issue for you!
